Push and pull remote cache per platform

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -38,8 +38,8 @@ jobs:
           path: ./.remote-cache
           key: ${{ runner.os }}-remote-cache
 
-      # - name: Pull cache 
-      #   run: $SBTN pullRemoteCache || echo 'remote cache not found'
+      - name: Pull cache 
+        run: $SBTN pullRemoteCache-$SCALA_PLATFORM || echo 'remote cache not found'
 
       - name: Test 2.12
         run: $SBTN "test-2_12-$SCALA_PLATFORM;codeQuality-2_12-$SCALA_PLATFORM"
@@ -59,7 +59,7 @@ jobs:
         if: matrix.scalaPlatform == 'jvm'
 
       - name: Push cache 
-        run: $SBTN pushRemoteCache || echo 'Failed to push remote cache'
+        run: $SBTN pushRemoteCache-$SCALA_PLATFORM || echo 'Failed to push remote cache'
         if: github.ref == 'refs/heads/master'
         
   mergify-build-checkpoint:
